### PR TITLE
Update card-image height

### PR DESCRIPTION
**Pull request by db118**
Addresses #56 

Updated card-image height in sponsor page
screen shot 2018-09-21 at 12 10 28 am

Updated card-image height in communities page
screen shot 2018-09-21 at 12 10 19 am

Signed-off-by: db118 <drrylbalderas@gmail.com>

## ✅️ By submitting this PR, I have verified the following

* [x] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
* [x] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/CONTRIBUTING.md) 🔍️
* [x] Added my name to the bottom of the list under the **Credits** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my website or GitHub profile 👥️

### CODE REVIEW

**Comment by fvcproductions** [comment]
The perspective is off now for images

**Comment by dvidsilva** [comment]
@fvcproductions Oh I didn't check well enough., @db118  can you try a fix?

**Comment by fvcproductions** [comment]
The images would have to be all be the same dimensions for them to all have same height unless we did background images which is why I didn't use the extra class.

**Comment by dvidsilva** [comment]
Ya background image is defi te way to go

**Comment by db118** [comment]
@dvidsilva Yeah I can fix  it 😄

**Comment by fvcproductions** [comment]
@db118 	@dvidsilva 	I am going to revert this until it's fixed in another PR since I want to share the website with some other Latinx folks and don't want them to see the images like that! 😛 👍

**Pull request merged**
