### PR TITLE
[UPDATE] - Header nav should be dropdown

### PR DESCRIPTION
**Pull request by cclaro**
@fvntr to add more submenu items please updated the config.toml file

### CODE REVIEW

**Comment by cclaro** [comment]
@fvcproductions will do the updates.
Yes, you will need to add the submenu items in the config file.

**Comment by fvcproductions** [comment]
@fvntr `config.toml` just needs to have all the children links defined unless a function is used in the HTML.

@cclaro Sounds good - thank you again - they are minor and mostly related to design and mobile-responsiveness.

**Comment by fvcproductions** [comment]
Closing in favor of #228 - thanks for your contributions @cclaro 😊

**Comment by cclaro** [comment]
Welcome @fvntr, sorry not getting back to you for the last updates, let me know if you still need some help on this.

**Pull request closed without merging**
