### PR TITLE
Nonprofit link added into navbar

### LINKED ISSUE #330: Add nonprofit link to navbar
## Feature Request

https://techqueria.org/resources/nonprofits should be added to dropdown navbar

## Any additional context?

See #323 for more context

### PR DESCRIPTION
**Pull request by teisenhower**
Added new link item in navbar for **Nonprofits page**
- Fixes #330        
````toml
[[menu.main]]
    name                             = "Nonprofits"
    url                              = "/resources/nonprofits/"
````

---

> ✅️ By submitting this PR, I have verified the following

- [x] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- [x] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- [x] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️

### CODE REVIEW

**Comment by fvcproductions** [comment]
@teisenhower looks like this was already added to the navbar so never mind! thanks for trying to make a contribution though and feel free to make another 🙌

**Comment by teisenhower** [comment]
@fvcproductions no worries! I would be up for taking #331 

If I may ask, was my solution to this request what you were looking for? The reason I ask is because this was my first time seeing that Hugo framework so I just want to be sure I handled it properly.

Thank you!

**Comment by fvcproductions** [comment]
The solution was almost 100% correct - you were just missing the parent param so that it was a child dropdown item. It was great - it just already existed!

**Comment by teisenhower** [comment]
Thank you!! That was 100% my confusion, I thought it needed to be in the main nav bar so I removed that parent parameter. But this makes perfect sense now because I did see this code already in there for Nonprofits underneath "Resources".
````toml
[[menu.main]]
    parent                           = "Resources"
    name                             = "Nonprofits 💛"
    url                              = "/resources/nonprofits/"
````
But thank you for letting me know! Your feedback is appreciated!

**Pull request closed without merging**
