### PR TITLE
emojis removed from nav bar dropdowns

### LINKED ISSUE #331: Remove emoji from navbar dropdowns
## Request

Let's remove emoji from dropdown navbar items

## Why did you make this request?

We want to come across as more professional 😂😬

## Any additional context?

N/A

### PR DESCRIPTION
**Pull request by teisenhower**
Emojis removed from items in dropdowns

- Fixes #331 
---

> ✅️ By submitting this PR, I have verified the following

- [x] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- [x] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- [x] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️

### CODE REVIEW

**Comment by fvcproductions** [comment]
@teisenhower could we also get the emojis removed from the spanish navbar version?

**Comment by teisenhower** [comment]
@fvcproductions my apologies! I'll remove them as well. Sorry for that oversight.

**Comment by fvcproductions** [comment]
no worries 😸

**Comment by teisenhower** [comment]
Emojis have been removed from Spanish nav bar as well. Thank you again!

**Comment by fvcproductions** [comment]
LGTM, thanks for the contributions!

**Comment by teisenhower** [comment]
Of course! Happy to be apart of it. Looking forward to another!

**Pull request merged**
