### PR TITLE
Issue#73

### PR DESCRIPTION
**Pull request by joaoluizn**
So, to solve the sponsor's logo cut off, I simply adjusted background size to "contain". In this case, when we are creating cards that have the same width and height, we may use images that follow some pattern. this could be noticed in communities page, where the images used, are wide and content centralized, that able us to "cover" it and give that feeling of full filling. But to really avoid cutting different sized pictures, i recommend use "contains", until find new pictures that follows the same pattern from communities page. The same will apply to events page, that pics are being cutted off. But i when i tried to simply change it, to contains, it is using the same reference from communities, so i recommend split then off. card-image-sponsors would became card-image-general (for sponsors and events), and card-image
 will be used on communities.

---

## ✅️ By submitting this PR, I have verified the following

* [✅️] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
* [✅️] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/CONTRIBUTING.md) 🔍️
* [✅️] Added my name to the bottom of the list under the **Credits** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my website or GitHub profile 👥️

### CODE REVIEW

**Comment by joaoluizn** [comment]
Yeah, I think new images would fit this. Should I try to find new pics, or have any special way to obtain them?

**Comment by fvcproductions** [comment]
@joaoluizn yeah I would just try and find some new pics - that way, we don't need a new class and it still resolves issue #73 since that only applies to a few companies in the first place 😄 

again, really appreciate the contribution - it'll just be easier to maintain if there's less classes

**Comment by joaoluizn** [comment]
Hey @fvcproductions, i found some pics that fit correctly, will pull a new patch in some minutes, i just can't find a ideal logo for informedk12, but i think all the others will deal the job.

**Comment by fvntr** [comment]
Can you add screenshots?

**Comment by fvcproductions** [comment]
@joaoluizn this looks great - thanks so much!

@fvntr no screenshots are needed, you can actually see the preview using Netlify under "Show all checks"

https://deploy-preview-76--techqueria.netlify.com/

**Pull request merged**
