### PR TITLE
Added new sponsor, and changed partner to past partners

### PR DESCRIPTION
**Pull request by michellbrito**
Added Ayden to the silver sponsor's section, and changed KeepTruckin to past partners

resolves https://github.com/techqueria/website/issues/822 
resolves https://github.com/techqueria/website/issues/841

Deploy preview: https://deploy-preview-834--techqueria.netlify.app/supporters/
 
---

> ✅️ By submitting this PR, I have verified the following

- [x] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️

- [x] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- [x] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️ (Optional)

### CODE REVIEW

**Comment by DianiSN** [comment]
Adding this here so it can be seen in the list of issues that there is a pull request for this one. Resolves #822

**Comment by michellbrito** [comment]
@all-contributors please add @michellbrito for adding silver sponsor

**Comment by michellbrito** [comment]
@all-contributors please add @michellbrito for maintenance

**Comment by fvntr** [comment]
lgtm

**Review by fvntr — APPROVED** [review]

**Pull request merged**
