### PR TITLE
Issue #189: updated resources under open-source

### PR DESCRIPTION
**Pull request by YourMobileGeek**
#### updated resources under open-source
---

> ✅️ By submitting this PR, I have verified the following

- [ ] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- [ ] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- [ ] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️

### CODE REVIEW

**Comment by fvcproductions** [comment]
@YourMobileGeek Looks great! The images don't seem to be showing up though - can you fix the path to link to the main techqueria image?

**Comment by YourMobileGeek** [comment]
Thanks for pointing this out! I'll go ahead double check the path now and will push the updates.

**Comment by YourMobileGeek** [comment]
screen shot 2018-12-04 at 8 31 18 pm

When running on localhost seems like the images appear, if changing it to another file directory path the images don't appear. 🧐

**Comment by fvcproductions** [comment]
Ah gotcha - I think the contributing docs could use a refresh on how images are added in because it's not clear enough right now tbh. 😝 

So the reason it works on localhost is probably because you put the image in the `dist` folder. Since the local server is just displaying everything in the `dist` folder, it will appear locally.

But if we want to show up in production as well as local - we need to add it to `src/img/` where it is then optimized by gulp tasks.

Right now, there's no image with the techqueria logo in https://github.com/techqueria/website/tree/master/src/img/resources or in your PR so it won't show on production. 

We can use the existing logos in `src/img` and update the paths to use one of those instead. 🙇‍♀️

**Comment by YourMobileGeek** [comment]
Okay gotcha, makes complete sense now haha. Thanks for keeping me up to date, I just submitted another PR with the updated image path referencing the `src/img/resources` folder

**Comment by fvntr** [comment]
any update on this?

**Comment by YourMobileGeek** [comment]
Thanks for following up! I was able to submit an updated PR a few days back, just waiting on feedback on the updated changes

**Comment by fvntr** [comment]
lgtm
thanks @YourMobileGeek !

**Pull request merged**
