### PR TITLE
Update homepage image

### PR DESCRIPTION
**Pull request by YourMobileGeek**
#### I ahead and switched out the homepage image provided through Google Photos for the Techqueria website.
---

## ✅️ By submitting this PR, I have verified the following

* [ ] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
* [ ] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/CONTRIBUTING.md) 🔍️
* [ ] Added my name to the bottom of the list under the **Credits** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my website or GitHub profile 👥️

### CODE REVIEW

**Comment by fvcproductions** [comment]
@YourMobileGeek Could we optimize the image for performance before it gets merged? Making it a smaller width and making it ~500KB in size would be best. We are adding an integration that will do this automatically but for now, that would be ideal!

**Comment by YourMobileGeek** [comment]
@fvcproductions Sounds good, I can go ahead and look into making it a smaller width, it regards to optimization to 500kb is there a workaround around for this you would suggest?

**Comment by fvntr** [comment]
I usually use tinypng.com
Heres is a 500kb version 
homepage 1

**Comment by YourMobileGeek** [comment]
@fvntr oh wow, yea I definitely overlooked that haha. I was thinking that you wanted to use another integration for the time being. Thanks! I'll go ahead and switch out this image and do a pull request.

**Pull request closed without merging**
