### PR TITLE
Fixes #294 Added non-profit resources

### LINKED ISSUE #294: Add non-profit resources
## Request

Look up all the resources provided below and add them to a new section of the website:

https://techqueria.org/resources/non-profits

## Resources

- Google for non profits
- Slack for non profits
- Facebook for non profits
- https://ycombinator.com/nonprofits
- https://microsoft.com/en-us/nonprofits
- https://gatesfoundation.org/How-We-Work/General-Information/Grant-Opportunities
- https://chanzuckerberg.com
- https://www.techsoup.org
- http://diversity.techstars.com/foundation
- http://praxislabs.org/nonprofit
- http://ffwd.org/accelerator
- http://tt-exchange.org

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

### PR DESCRIPTION
**Pull request by sonali9696**
Fixes #294 

This creates a new page with the URL: https://techqueria.org/resources/nonprofits. This page is populated with 12 non-profits in a card format with their logos, descriptions and link to their websites. They are as follows:

1. - Google for non profits
2. - Slack for non profits
3. - Facebook for non profits
4. - https://ycombinator.com/nonprofits
5. - https://microsoft.com/en-us/nonprofits
6. - https://gatesfoundation.org/How-We-Work/General-Information/Grant-Opportunities
7. - https://chanzuckerberg.com
8. - https://www.techsoup.org
9. - http://diversity.techstars.com/foundation
10. - http://praxislabs.org/nonprofit
11. - http://ffwd.org/accelerator
12. - http://tt-exchange.org

---
> ✅️ By submitting this PR, I have verified the following

- [x] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- [x] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- [x] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️

### CODE REVIEW

**Comment by sonali9696** [comment]
I have added the emoji beside the title but it is not visible properly due to the background color so I would suggest using some other emoji or colour. LMK what you think. (Also I will be on vacation from today 4 pm till April 20th, so I may not be able to push any new changes during this gap since I won't have my laptop or internet due to hilly terrain).

image

**Comment by sonali9696** [comment]
I corrected the emoji issue by placing it next to the title, instead of wrongly putting it after description:
image

If you still need me to change the color of the emoji or the emoji itself, please LMK

**Comment by sonali9696** [comment]
I have made and pushed all the changes that you had requested. I would be leaving in 2 hours to catch my flight. I will make any more changes if needed once I am back after 21st. Have a great week ahead!  :)

**Comment by fvcproductions** [comment]
@sonali9696 Updates look great! The only thing missing is adding the link to the navbar

**Comment by fvcproductions** [comment]
Let's add this in for now and create an issue to get it added to navbar later 👍🏽

**Pull request merged**
