### PR TITLE
31 add gina testimonial

### PR DESCRIPTION
**Pull request by SneX13**
Remove this sentence and insert the description of the pull request here.

---

> ✅️ By submitting this PR, I have verified the following

- [x] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
- [x] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md) 🔍️
- [x] Added my name to the bottom of the list under the **Contributors** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my personal website or GitHub profile 👥️

### CODE REVIEW

**Comment by fvntr** [comment]
I will try and get you a more reliable image

**Comment by fvcproductions** [comment]
@fvntr @SneX13 We can just download the one from LinkedIn and upload it to Imgur and link that URL instead.

**Comment by SneX13** [comment]
Thank you @fvntr. I just linked LinkedIn img, but I would be fine you have a place for storing imgs (i.e on some server) or I can always save it in a code and you will be sure that it is there.

**Comment by SneX13** [comment]
> @fvntr @SneX13 We can just download the one from LinkedIn and upload it to Imgur and link that URL instead.

Ok, then I will do it like that. Thanks!

**Pull request merged**
