### PR TITLE
Implement initial donate section

### PR DESCRIPTION
**Pull request by darrylbalderas**
Addressing issue #89 

Signed-off-by: darrylbalderas <drrylbalderas@gmail.com>

---

## ✅️ By submitting this PR, I have verified the following

* [x] Checked to [see if a similar PR has already been opened](https://github.com/techqueria/website/pulls) 🤔️
* [x] Reviewed the [contributing guidelines](https://github.com/techqueria/website/blob/master/CONTRIBUTING.md) 🔍️
* [x] Added my name to the bottom of the list under the **Credits** section in the [README.md](https://github.com/techqueria/website/blob/master/README.md) with a link to my website or GitHub profile 👥️

### CODE REVIEW

**Comment by darrylbalderas** [comment]
@fvcproductions

**Comment by fvcproductions** [comment]
@darrylbalderas Great PR, a few recommendations:

- this section might be better served under the "Sponsor" section actually since Patreon only allows for on-going contributions
- link should be external `target="_blank"` and have a `rel="noopener` as well for security
- copy might need to be revised to provide more context
- height should be in `rem` so it's more responsive - I recommend `height: 3rem`

"You can also support Techqueria's efforts by becoming an ongoing patron via Patreon." versus "Any monetary contribution is greatly appreciated."

screenshot 2018-10-21 19 15 34

**Comment by fvcproductions** [comment]
@darrylbalderas Great PR, a few recommendations:

- this section might be better served under the "Sponsor" section actually since Patreon only allows for on-going contributions
- link should be external `target="_blank"` and have a `rel="noopener` as well for security
- copy might need to be revised to provide more context
- height should be in `rem` so it's more responsive - I recommend `height: 3rem`

"You can also support Techqueria's efforts by becoming an ongoing patron via Patreon." versus "Any monetary contribution is greatly appreciated."

screenshot 2018-10-21 19 15 34

**Comment by fvcproductions** [comment]
@darrylbalderas Great PR, a few recommendations:

- this section might be better served under the "Sponsor" section actually since Patreon only allows for on-going contributions
- link should be external `target="_blank"` and have a `rel="noopener` as well for security
- copy might need to be revised to provide more context
- height should be in `rem` so it's more responsive - I recommend `height: 3rem`

"You can also support Techqueria's efforts by becoming an ongoing patron via Patreon." versus "Any monetary contribution is greatly appreciated."

screenshot 2018-10-21 19 15 34

**Comment by fvcproductions** [comment]
@darrylbalderas Great PR, a few recommendations:

- this section might be better served under the "Sponsor" section actually since Patreon only allows for on-going contributions
- link should be external `target="_blank"` and have a `rel="noopener` as well for security
- copy might need to be revised to provide more context
- height should be in `rem` so it's more responsive - I recommend `height: 3rem`

"You can also support Techqueria's efforts by becoming an ongoing patron via Patreon." versus "Any monetary contribution is greatly appreciated."

**Comment by fvcproductions** [comment]
Thanks for being so receptive to feedback @darrylbalderas - much appreciated!

**Pull request merged**
